/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
<<<<<<< Updated upstream
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCarousel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UChatMessages: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatMessages.vue')['default']
    UChatPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatPalette.vue')['default']
    UChatPrompt: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UCommandPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UContainer: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULink: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPageCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/PageCard.vue')['default']
    UPageHero: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jw_e2bb8033560662426afabb5f89672e5d/node_modules/@nuxt/ui-pro/dist/runtime/components/PageHero.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USkeleton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTabs: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_04eeb33777c46e00b07af85a42d8f244/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
=======
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCarousel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UChatMessages: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescrip_d2d075cac126be02e27e7deb5d140bb4/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatMessages.vue')['default']
    UChatPrompt: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescrip_d2d075cac126be02e27e7deb5d140bb4/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescrip_d2d075cac126be02e27e7deb5d140bb4/node_modules/@nuxt/ui-pro/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UCommandPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UContainer: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_typescript@5.7.3_vite@6.3.5_@t_47aa12c077876042a4e7c9d0e5719657/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPageHero: typeof import('./../../node_modules/.pnpm/@nuxt+ui-pro@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescrip_d2d075cac126be02e27e7deb5d140bb4/node_modules/@nuxt/ui-pro/dist/runtime/components/PageHero.vue')['default']
    USelectMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USkeleton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_embla-carousel@8.6.0_jwt-decode@4.0.0_typescript@5._474a070a8e07323774d920de603ae347/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
>>>>>>> Stashed changes
  }
}
