packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 1.9.4
  '@types/node': ~20.10.8
  typescript: ~5.7.3

catalogs:
  vue:
    '@vueuse/core': ^13.3.0
    vue-router: ^4.5.1
    vue: ^3.5.16
